### PR TITLE
Refactor as stand-alone rock

### LINKED ISSUE #37: Help with fontproof API changes and long-term maintainership
Hi Caleb,

I've been trying to get fontproof to follow the recent API changes but I'm now stuck with how new packages are designed to work. 
Victor - the original author - isn't able to dedicate time to this, so we think it would be great if you could take a look and if fontproof just became one of the packages/classes who are part of sile rather than a separate project. You are most definitely the best person to keep up with the API changes so fontproof can continue working as expected. Thank you for considering it. 

Other fontproof related issues: https://github.com/sile-typesetter/sile/issues/722 and https://github.com/sile-typesetter/sile/issues/797 

Thanks!

### PR DESCRIPTION
**Pull request by alerque**
Closes #37

Not ready for primetime yet, but

``` console
$ make install
$ ./lua_modules/bin/fontproof -h
Usage: fontproof [OPTIONS] [--] [SILEARGS]

ARGUMENTS:
  SILEARGS             All remaining args are passed directly to SILE
                       (optional)

OPTIONS:
  -f, --filename=VALUE Specify the font to be tested as a path to a
                       font file
  -F, --family=VALUE   Specify the font to be tested as a family name
  -o, --output=FILE    output file name
  -s, --size=VALUE     Specify the default test font size
  -t, --template=VALUE Use the bundled template by name (full,
                       gutenberg, test, unichar);
  -h, --help           display this help, then exit
```

### CODE REVIEW

**Comment by alerque** [comment]
Testing against old versions of SILE might be pretty tricky. We'd probably have to checkout and build the sources for them directly. I might ditch that and just test on the latest to get v2 of this project spun up with a clear path to iterating on small improvements from there. The v2 series will not be compatible with very old versions anyway, basically you'll need at least v0.14.0 just to play and there isn't much point in not running the latest patches on top of that, so this probably wont' be much of a loss until v0.15.0 comes out.

**Comment by alerque** [comment]
I'll probably move ahead with this and work on getting all the moving parts in place for a v2 release to LuaRocks.org. Anybody currently using this is almost certainly doing so with old packages and and old SILE to match. Anybody coming along right now and trying to match it to a new SILE is just going to find everything broken. And on top of that nobody else can iterate on smaller improvements like templates and commands without the overall project layout being fixed up. Even if v2.0.0 isn't perfect it should give a working tool that people can easily improve and contribute to again.

**Comment by alerque** [comment]
For testing even prior to v2.0.0 tagging, the Docker image for this should be available as the HEAD build now:

``` console
$ docker pull ghcr.io/sile-typesetter/fontproof:master
$ alias 
```

And also the dev rockspec is available [on LuaRocks](https://luarocks.org/modules/sile-typesetter/fontproof):

``` console
$ luarocks install fontproof dev-1
```

**Comment by n7s** [comment]
After installing the rock I'm able to test the new fontproof on some font existing font projects.

Looks like when a .sil test file (which we tend to keep under tests/example.sil in various font project repositories) has something like `\setTestFont[features="+clig,+kern",size="18pt"] ` I get this error: `Using code at: /usr/local/share/lua/5.2/sile/classes/fontproof/init.lua:127: attempt to concatenate field 'family' (a nil value)`

Other test files give me errors like:` Failed to load any working font manager`  or `Using code at: /usr/share/sile/outputters/libtexpdf.lua:30: attempt to index field 'paperSize' (a nil value)`

What  am I missing? What am I doing wrong? I'm just trying `fontproof tests/document.sil -f "./results/font-file.ttf -o results/example-result.pdf`

It would be ideal to be able to reuse existing .sil documents which have `\setTestFont[params]` and not to have to change them all. 

How do I set the family field or the font manager? Isn't the papersize field already defined in the package? 

One simple example is https://github.com/silnrsi/font-andika-mtihani/blob/master/tests/Latin.sil 

Thank you for any insights and tips. 

Also I'm quite happy if fontproof just becomes an in-tree package/class and is bundled inside SILE itself. IMHO there is no big need for it to be a standalone package. 

Çok teşekkür ederim!

**Pull request merged**
