### PR TITLE
Setup Docker container with SILE + Fontproof and make it possible to run as a GitHub Action

### PR DESCRIPTION
**Pull request by alerque**
This PR:

- [x] Adds a `Dockerfile` that takes the Docker container for SILE as a base and adds in fontproof. The method is a little unorthodox, but I expect the current SILE package system to get replaced and it isn't very useful for this purpose because we want to match versions of fontproof with Docker containers of the same version so that downstream project cat get repeatable results with their preferred version of fontproof.

- [x] Adds a `Makefile` that is purely developer convenience, and is mostly useful for building a Docker image locally. Most people will probably full a prebuilt one from docker.io, but for testing it's handy to be able to run `make docker`.

- [x] Configures this repository so it can be used *as* a GitHub Action. This will make it trivially easy for font project repositories to setup CI workflows that test their font projects using Fontproof.

If you are interested in this, I'll need a couple things to be done by somebody at SIL.

- [x] Setup an org at Docker Hub and either configure it to build containers from this repository. I can provide exact instructions or add my user with permissions to set it up.

- [x] Update the generated image name and documentation with whatever was actually used to register, I've just filled in a guess right now (`silnrsi/fontproof`).

- [x] Change maintainer info in the Dockerfile to whoever is responsible for the Docker Hub registry.

Additional tidbits that could be done to round this out:

- [x] Document how to use it as a GitHub Action from a font project repository.

- [x] Document how to run a specific version (HEAD vs. latest vs. any tagged version).

### CODE REVIEW

**Comment by alerque** [comment]
P.S. This ground work would be pretty easy to extend for use on almost any other CI platform. I just started with GH Actions because this repo is hosted on GH.

**Comment by jvgaultney** [comment]
We'll consider this, but it may take a while to discuss among us. Thanks.

**Comment by devosb** [comment]
SIL would be happy if you want to clone FontProof to your personal GitHub account (or the sile-typesetter account) and setup Docker as you described. Future changes to FontProof are going to be driven by changes to SILE, since you are the one working on SILE, it makes sense for you to control the testing setup.

An alternative is to move FontProof into SILE itself. Since FontProof is one of the few products using the SILE extension mechanism, moving the code might make future development and maintenance easier.

**Comment by devosb** [comment]
@alerque which option do you prefer 1) cloning FontProof somewhere you control and running Docker or 2) moving FontProof into the SILE repo?

**Comment by alerque** [comment]
I think I'd prefer the latter, but perhaps with whatever SIL people are relevant keeping their collaborator access to it. I feel like as the first and still largest *user* of this package you guys should have a major voice in its future development. I've been helping fix and upgrade stuff since I understand the upstream changes that it needs to be adapted for, but that doesn't mean I have the best view of how it's useful on the ground. Of course even if I do something stupid as maintainer that works against your usage you can always keep running on a fork, but I'd rather stay in the cooperative/collaborative mode.

@simoncozens how do you feel about transferring this repo into the @sile-typesetter org and giving the current active SIL developers access to it there.

**Comment by simoncozens** [comment]
I think it makes sense if they do!

**Comment by alerque** [comment]
@devosb I've sent invites to you and 3 other SIL folks I see that are contributors here to join the @sile-typesetter org; where I have also setup an SILWSTech team that I'll add you to and make admins on the repo after transfer. Once you join you should have enough permissions to transfer this repository to the org namespace. GitHub does a pretty good job of setting up automatic redirects so everybody's links (including forks and clones) will keep functioning.

**Comment by devosb** [comment]
@alerque thank you for the invitations. I may not have been clear in my options. We were thinking that maybe the code of FontProof would move into the [SILE repo](https://github.com/sile-typesetter/sile) (not just the [SILE Typesetter org](https://github.com/sile-typesetter)). That way, FontProof would be a native package to SILE, and when SILE changed, the code for FontProof could change as well.

But moving the FontProof repo to the SILE Typesetter org works very well for us, and sounds like would easier than the above (the history would presumably stay intact, and redirects would be enabled as you mention). With this approach, please change FontProof as needed to keep up with changes to SILE. Our team is using a released version of SILE (from your PPA) so we would probably need to also use a released version of FontProof. Otherwise, having a released version of SILE might not support the latest changes to FontProof.

**Comment by alerque** [comment]
> @alerque thank you for the invitations. I may not have been clear in my options. We were thinking that maybe the code of FontProof would move into the [SILE repo](https://github.com/sile-typesetter/sile) (not just the [SILE Typesetter org](https://github.com/sile-typesetter)). That way, FontProof would be a native package to SILE, and when SILE changed, the code for FontProof could change as well.

I did not understand that. Certainly moving packages into the core distribution is something we've both done in some cases and considered in more. I hadn't seriously considered it in this case for several reasons. I don't think it's a great fit for that:

* It's really more used as a stand alone tool that depends on SILE rather than the other way around.
* People wouldn't include this package to extend the functionality of SILE for use in their existing (or new) documents. It basically creates it's own.
* I see lots of utility it having at a stand alone tool that can do things outside of the limited scope of a single document.
* The release cadence fo SILE core is not a good fit for packages like this that may very well see development work by other developers and it could make sense to release this more often than SILE itself or at points where SILE just isn't cleaned up and ready for a release.

> But moving the FontProof repo to the SILE Typesetter org works very well for us, and sounds like would easier than the above (the history would presumably stay intact, and redirects would be enabled as you mention). With this approach, please change FontProof as needed to keep up with changes to SILE. Our team is using a released version of SILE (from your PPA) so we would probably need to also use a released version of FontProof. Otherwise, having a released version of SILE might not support the latest changes to FontProof.

Yes the history would stay intact, and with repository transfer all the existing linkage will keep working. It should be a zero interruption way to get rolling.

**Comment by jvgaultney** [comment]
I've transferred the repo. Thanks!

**Comment by alerque** [comment]
Thanks @jvgaultney. I think you and some others should have all the access you need to keep developing and even manage people on the team that has access to this repository, but feel free to holler in an issue if you need anything.

I've make the necessary adjustments to scope and namespaces for this to work — I think. Unfortunately I can't make Docker Hub test build this PR before a Dockerfile lands in master, so I'm going to go ahead and merge early and touchup later if necessary.

**Comment by jvgaultney** [comment]
Thanks - that's fine with us.

**Pull request merged**
