### PR TITLE
Update for SILE v0.13.0

### PR DESCRIPTION
**Pull request by alerque**

### CODE REVIEW

**Comment by alerque** [comment]
The current code seems to run just fine with SILE v0.13.0, but it is functioning only with the shim in place upstream for making old style classes work in the new system. Even the CI tests show us spewing warnings about the deprecations.

I can easily rewrite the FontProof class to use the new system, but once we do that we will break compatibility with older versions of SILE.

I suppose the best thing to do might be to hold out with things as they are in this package for a little bit to let v0.13.0 roll out to as many fontproof users as possible (it was released a week ago and most platforms got it right away but I only just got the Ubuntu builds updated in the PPA), then update the classes sometime before v0.14.0 hits.

Thoughts anyone?

**Comment by n7s** [comment]
Our toolchain is currently flagging these issues when using 0.13.1-1ppa1~ubuntu20.04 (from the Ubuntu PPA which we are using, IOW we are getting updates and are not pinning a particular version of SILE): 

!     Use of SILE.require() is only supported in documents, packages, or class
      init functions. It cannot be used before the class is instantiated.
      Please just use the Lua require() function directly.
      SILE.require("classes/plain") → require("classes/plain")

!     The document class inheritance system for SILE classes has been
      refactored using a different object model. Your class (fontproof), has been
      instantiated with a shim immitating the stdlib based model, but it is
      *not* fully backwards compatible, *will* cause unexpected errors, and
      *will* eventually be removed. Please update your code to use the new
      Penlight based inheritance model.

std.object() was deprecated in SILE v0.13.0. Please use pl.class() instead. 
! SILE.settings.*() was deprecated in SILE v0.13.0. Please use SILE.settings:*() instead. 
! SILE.settings.*() was deprecated in SILE v0.13.0. Please use SILE.settings:*() instead. 

This results in the builds of 11 font projects failing. 

I think updating fontproof to follow the SILE classe changes is good to do. I don't know that we have many users who are stuck with an older version and are unable to upgrade to the newest SILE. It will be much easier for you to take care of that than for me, no doubt. What do you think @jvgaultney ?

We are currently still at v1.5.0 in the [sile-packages catalog](https://github.com/sile-typesetter/sile-packages/) and I think we need to drop that line: https://github.com/sile-typesetter/sile-packages/blob/d9a7456c554dfb3da778f13e03d8f1469ad3c8bd/packages.lua#L10 so that updates can flow without having to change the catalog with every release/fontproof fix.

**Comment by jvgaultney** [comment]
I think that having Caleb update fontproof to use the new classes would be good as SILE approached 0.13 and the shims are removed, and that we don't need to worry about backward compatibility. However we do need an *immediate* solution for our current build failures with 0.13.1.

**Comment by n7s** [comment]
Could you clarify what you mean by the **shim in place upstream**? This should be in the Ubuntu package, right? What am I missing?  Any clues about the cassowary error?

**Comment by n7s** [comment]
After looking at the repo and the docs some more I see what you mean with the shims.

**Comment by devosb** [comment]
I fixed the deprecation warnings (please check my work in [sile-0.13.txt](https://github.com/sile-typesetter/fontproof/files/8943694/sile-0.13.txt)) and the cassowary error went away as well. I did not commit these changes, nor create a PR, because I still could not get FontProof to work.

I used the environment variable `SILE_PATH` so SILE could find FontProof. And SILE apparently read this variable, otherwise, how would have my changes made a difference? But after making the errors and warnings go away, SILE says
```
	/usr/share/sile/core/sile.lua:147: module 'fontproof' not found:
	no field package.preload['fontproof']could not load `ftl` file
```
I ran `sudo install -m 644 classes/fontproof.lua /usr/share/sile/classes` but this did not help.

I ran `sudo install -m 644 classes/fontproof.lua /usr/share/sile` and this had an affect. SILE said
```
Error detected:
	error loading module 'fontproof' from file '/usr/share/sile/fontproof.lua':
	/usr/share/sile/fontproof.lua:206: function arguments expected near '['
```
[Line 206](https://github.com/sile-typesetter/fontproof/blob/master/classes/fontproof.lua#L206) does have some brackets `[]`

**Comment by alerque** [comment]
If backwards compatibility isn't an issue just updating the class ASAP is probably the thing to do. I'll get on that right now...

**Comment by alerque** [comment]
I just applied the patch from @devosb, then fixed the bits that needed more TLC than a global search and replace ;-).

After that I rewrote the class to use the new Penlight object inheritance model. This means that it is now only SILE >= 0.13 compatible, but I suspect it will be easier to just get people to update SILE than it will be to try to do a patch release that supports the intermediate shims only to have to upgrade everything eventually anyway.

For my part I'll help keeping this working on current versions but supporting old versions because people don't want to upgrade anything else is probably more than I have time for. I already put *weeks* into making 0.13 break as few things as possible and adding shims so many projects would just keep working, but I know it didn't cover all cases and eventually had to move ahead or it was just never going to happen, which wasn't fair to projects wanting new features.

**Comment by alerque** [comment]
Sure, feel free to drop the release pinning there.

Also the big feature for 0.14 is going to be a sane package manager that works without root `git` access (like you seem to be doing) or SILE monkey patching (like the Docker container for this project does).

**Comment by alerque** [comment]
Do you guys want me to go ahead and get this in a major release bump? Or do you want me to cherry pick the SILE 0.12.x compatible fixes into a patch release first and save the SILE 0.13 exclusive change for a subsequent bump?

**Comment by jvgaultney** [comment]
Huge thanks to you for doing all this improvement work. Yes please go ahead and make this a v1.6 release - no need to do a patch first.

**Comment by alerque** [comment]
@devosb The cassowary bug is completely independent. It is fixed in 2.3.2 but for some reason it looks like that build didn't make it into [the PPA](https://launchpad.net/~sile-typesetter/+archive/ubuntu/sile) for all Ubuntu versions. I'll look into that:

```
lua-cassowary 	2.3.2-1ppa1~ubuntu22.10
lua-cassowary 	2.3.1-0ppa4~ubuntu18.04
lua-cassowary 	2.3.1-0ppa2~ubuntu22.04
lua-cassowary 	2.3.1-0ppa2~ubuntu21.10
lua-cassowary 	2.3.1-0ppa2~ubuntu20.04
lua-cassowary 	2.3.1-0ppa1~ubuntu21.04
```

**Pull request merged**
